laundryProject/helpapp/urls.py
from django.urls import path
from . import views


app_name = 'helpapp'

urlpatterns = [
    path('', views.helpapp, name='helpapp'),
    path('nologin', views.nologin, name='nologin'),
    path('home', views.home, name='home'),
    path('washer', views.washer, name='washer'),
    path('cabinet', views.cabinet, name='cabinet'),
    path('register', views.register, name='register'),
    path("user/",views.user, name="user"),
    path("judge",views.judge, name="judge"),
    path("judge_result",views.judge_result, name="judge_result"),
    path("judge_report",views.judge_report, name="judge_report"),
    path("cabinet_judge",views.cabinet_judge, name="cabinet_judge"),
    path("cabinet_form",views.cabinet_form, name="cabinet_form"),
    path("cabinet_add",views.cabinet_add, name="cabinet_add"),
    path("cabinet_detail/<int:pk>/",views.cabinet_detail, name="cabinet_detail"),
    path("washer_add",views.washer_add, name="washer_add"),
    path("washer_add_redirect",views.washer_add_redirect, name="washer_add_redirect"),
    path("washer_judge",views.washer_judge, name="washer_judge"),
    path("washer_complete",views.washer_complete, name="washer_complete"),
    path("washers_delete",views.washers_delete, name="washers_delete"),
    path("washer_clear",views.washer_clear, name="washer_clear"),
    path("laundry_tag_check",views.laundry_tag_check, name="laundry_tag_check"),
    path("cabinet_delete/<int:pk>/",views.cabinet_delete, name="cabinet_delete"),
    path("cabinets_delete",views.cabinets_delete, name="cabinets_delete"),
    path("test",views.testYolo, name="test"),
    path("washer_log_add",views.washer_log_add, name="washer_log_add"),
    path("washer_log",views.washer_log, name="washer_log"),
    path("washer_log_detail/<int:pk>/",views.washer_log_detail, name="washer_log_detail"),
    path("washer_log_delete/<int:pk>/",views.washer_log_delete, name="washer_log_delete"),
    path("log_to_washer/<int:id>/",views.log_to_washer, name="log_to_washer"),
    path("report_admin",views.report_admin, name="report_admin"),
    path("report_commit",views.report_commit, name="report_commit"),
]

laundryProject/laundryProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('helpapp/', include('helpapp.urls')),  #URLにhelpapp/って指定されたら includeを呼び出す
    path('admin/', admin.site.urls),    #admin入るため
    path('', RedirectView.as_view(url='/helpapp/')), #URLに何も入れないとhelpapp/になる
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像読むのに必要

laundryProject/helpapp/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User

class Categories(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class Report(models.Model):
    image = models.CharField(max_length=255)
    ai_result = models.CharField(max_length=255)
    user_result = models.CharField(max_length=255)
    annotation = models.BooleanField(default=False)
    def __str__(self):
        return str(self.id)


class Cabinet(models.Model):
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Categories,
        on_delete=models.PROTECT,
    )
    name = models.CharField(max_length=255)
    laundry_tag = models.CharField(max_length=255)
    image = models.ImageField(upload_to='img/', default='static/upload_img/img/image.jpg')
    memo = models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return str(self.author)

class Profile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
    )
    image = models.ImageField(upload_to='icon/', blank=True, null=True)
    judge_cnt = models.IntegerField(default=0)
    washer_cnt = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.user)

class Washer_log(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

class Laundry(models.Model):
    washer_log = models.ForeignKey(
        Washer_log,
        on_delete=models.CASCADE,
        related_name='washer_log_id'
    )
    cabinet = models.ForeignKey(
        Cabinet,
        on_delete=models.CASCADE,
        related_name='cabinet_id'
    )
    def __str__(self):
        return str(self.washer_log_id)

laundryProject/helpapp/forms.py
from django import forms
from .models import Cabinet,Profile,User
from django.contrib.auth.forms import PasswordChangeForm

class JudgeForm(forms.Form):
    UploadImg = forms.FileField()

class CabinetForm(forms.ModelForm):
    class Meta:
        model = Cabinet
        fields = ['image','name' ,'category', 'memo']
        widgets = {
            'memo': forms.Textarea
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class CabinetCategoryFrom(forms.ModelForm):
    class Meta:
        model = Cabinet
        fields = ['category']

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control' }))

    class Meta:
        model = User
        fields = ['username']


class UpdateProfileForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    
    class Meta:
        model = Profile
        fields = ['image']


class MyPasswordChangeForm(PasswordChangeForm):

    # テンプレートにおいて表示されるinputタグのカスタマイズは以下のように行う（下は一例）
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['class'] = 'old'# classの指定
        self.fields['new_password1'].widget.attrs['class'] = 'new'
        self.fields['new_password2'].widget.attrs['class'] = 're'
        self.fields['new_password1'].widget.attrs['placeholder'] = '半角英数字８文字以上'# placeholderの指定
        self.fields['new_password2'].widget.attrs['placeholder'] = 'パスワード確認用'

laundryProject/helpapp/views.py
import os
import shutil
from django.urls import reverse
from urllib.parse import urlencode
from django.shortcuts import render
from laundryProject.settings import MEDIA_ROOT
from .models import Cabinet, Categories, Profile, Washer_log, Laundry, Report
from django.shortcuts import redirect, render, get_object_or_404
from .forms import CabinetForm, JudgeForm, UpdateUserForm, UpdateProfileForm, MyPasswordChangeForm,CabinetCategoryFrom
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
import json
from PIL import Image
from PIL.ExifTags import TAGS
from helpapp.data_load import MODEL,tables,taginfo

def helpapp(request):
    #ログインがあるか判別
    if request.user.is_authenticated :
        return home(request)
    else :
        return redirect('/accounts/login/')

def register(request):
    return render(request, 'helpapp/register.html')

def nologin(request):
    context = {
        'ON' : json.dumps('home'),
        'message': 'Judge',
        'form': JudgeForm(),
        'tables': tables,
    }
    return render(request, 'nologin/index.html', context)

def home(request):
    if request.user.is_authenticated :
        if Profile.objects.filter(user=request.user).exists():
            context = {
                'ON' : json.dumps('home'),
                'message': 'Judge',
                'form': JudgeForm(),
            } 
        else:
            new_profile=Profile()
            new_profile.user = request.user
            new_profile.image = "none"
            new_profile.save()
            return redirect('/helpapp/home')
        return render(request, 'home/index.html', context)
    else :
        return redirect('/helpapp/nologin')

def washer(request):
    if request.user.is_authenticated :
        washers =[]
        tags=[]
        i=0
        none=1
        if 'washers' in request.session:
            IDs = request.session.get('washers')
            for id in IDs:
                if Cabinet.objects.filter(pk=id).exists():#存在確認
                    washers.append(Cabinet.objects.get(pk=id))
            for washer in washers:
                tags = washer.laundry_tag.split(',')
                washers[i].laundry_tag = tags[0]
                i+=1
        categories = Categories.objects.all()
        categories_json =[]
        
        for category in categories:
            categories_json.append(category.name)
        if len(washers) == 0:
            none = 0
        context = {
            'categories_json' : json.dumps(categories_json), 
            'categories' : categories,
            'ON' : json.dumps('washer'),
            'message': 'Washer',
            'none' : none,
            'none_json' : json.dumps(none),
            'washers' : washers
        }
        IDs = request.session.get('washers')
        return render(request, 'washer/index.html',context)
    else :
        return redirect('/accounts/login/')

def washer_add(request):
    if request.user.is_authenticated :
        user = request.user
        cabs = Cabinet.objects.filter(author=user)  
        cabs = list(cabs.values())
        if 'washers' in request.session:
            IDs = request.session.get('washers')  
            for ID in IDs :
                i=0
                for cab in cabs :
                    if int(ID) == int(cab["id"]) :
                        del cabs[i]
                        break
                    i += 1
        cabinets =[]
        for cabinet in cabs :
            tags = cabinet["laundry_tag"].split(',')
            if not(tags[0] == 'LD' or tags[0] == 'LE'):
                cabinets.append(Cabinet.objects.get(pk=cabinet["id"]))
        error=0
        if(len(cabinets) == 0):
            error = 1
        context = {
            'ON' : json.dumps('washer'),
            'message': 'Washer',
            'cabinets' : cabinets,
            'user' : user,
            'error' : error
        }
        return render(request, 'washer/add.html',context)
    else :
        return redirect('/accounts/login/')

def washer_add_redirect(request):
    if request.user.is_authenticated :
        # del request.session['washers']
        if request.method == "POST":
            checks_value = request.POST.getlist('check')
            washers = request.session.get('washers')
            if washers != None:
                for value in checks_value:
                    washers.append(value)
            else:
                washers = checks_value
        request.session['washers'] = list(set(washers))
        messages.success(request, '追加しました。')
        return redirect('/helpapp/washer')
    else :
        return redirect('/accounts/login/')

def washer_judge(request):
    if request.user.is_authenticated :
        if 'washers' in request.session:
            washers=[]
            IDs = request.session.get('washers')
            for id in IDs:#washersを取り出す
                if Cabinet.objects.filter(pk=id).exists():
                    washers.append(Cabinet.objects.get(pk=id))
            comp = ["L1", "B1", "T1"]
            L=[]
            L_washer=[]
            B=[]
            B_washer=[]
            T=[]
            T_washer=[]
            
            for washer in washers:
                tags = washer.laundry_tag.split(',')
                washer.laundry_tag = washer.laundry_tag.split(',')
                for tag in tags:
                    if tag[0] == "L":
                        L.append(tag[1])
                        L_washer.append(washer.id)
                        if int(tag[1], 16) > int(comp[0][1] ,16):#一番条件が厳しいタグの判定
                            comp[0]=tag
                    elif tag[0] == "B":
                        B.append(tag[1])
                        B_washer.append(washer.id)
                        if int(tag[1], 16) > int(comp[1][1] ,16):#一番条件が厳しいタグの判定
                            comp[1]=tag
                            
                    elif tag[0] == "T":
                        T.append(tag[1])
                        T_washer.append(washer.id)
                        if int(tag[1], 16) > int(comp[2][1] ,16):#一番条件が厳しいタグの判定
                            comp[2]=tag

            # zipで一つの変数"zip_lists"にまとめる
            # ソートの基準としたいリストを一番左においてzip
            zip_lists = zip(L, L_washer)
            # 昇順でソート
            zip_sort = sorted(zip_lists)
            # zipを解除
            L, L_washer = zip(*zip_sort)

            zip_lists = zip(B, B_washer)
            zip_sort = sorted(zip_lists)
            B, B_washer = zip(*zip_sort)
            
            zip_lists = zip(T, T_washer)
            zip_sort = sorted(zip_lists)
            T, T_washer = zip(*zip_sort)        

            context = {
                'washers' : washers,
                'comp' : comp,
                'comp_json' : json.dumps(comp),
                'ON' : json.dumps('washer'),
                'L_washer' : L_washer,
                'B_washer' : B_washer,
                'T_washer' : T_washer,
                'message': 'Washer',
                'taginfos' : taginfo,
            }
            return render(request, 'washer/result.html', context)
        return redirect('/helpapp/washer')
    else :
        return redirect('/accounts/login/')

def washer_complete(request) :
    if request.user.is_authenticated :
        profile = Profile.objects.filter(user=request.user).first()
        profile.washer_cnt += 1
        profile.save()
        return redirect('/helpapp/washer')
    else :
        return redirect('/accounts/login/')

def washers_delete(request):
    if request.user.is_authenticated :
        if request.method == "POST":
            check_values = list(set(request.POST.getlist('check')))
            washers = request.session.get('washers')
            for value in check_values:
                if value in washers:
                    washers.remove(value)
            request.session['washers'] = list(set(washers))
            messages.success(request, '削除しました')
            return redirect('/helpapp/washer')
    else :
        return redirect('/accounts/login/')

def washer_log(request):
    if request.user.is_authenticated :
        user = request.user
        laundries=[]
        washer_logs = []
        if Washer_log.objects.filter(user=user).exists():   #存在確認
            washer_logs = Washer_log.objects.filter(user=user).order_by("-created_at")
            for washer_log in washer_logs:
                if  Laundry.objects.filter(washer_log_id = washer_log.pk).exists():   #存在確認
                    laundries.append(Laundry.objects.filter(washer_log_id = washer_log.pk)) #laundry表とcabinet表を結合
                else :
                    washer_log.delete()
        none = ""
        if len(washer_logs) == 0:
            none = 0
        context = {
            'ON' : json.dumps('bookmark'),
            'message': 'Bookmark',
            'none': none,
            'washer_logs' : washer_logs,
            'Laundries' : laundries,
            'user' : user,
        }
        return render(request, 'washer_log/index.html', context)
    else :
        return redirect('/accounts/login/')

def washer_log_add(request):
    if request.user.is_authenticated :
        if 'washers' in request.session:
            Laundries=[]
            IDs = request.session.get('washers')
            for id in IDs:
                if Cabinet.objects.filter(pk=id).exists():
                    Laundries.append(Cabinet.objects.get(pk=id))
            washer_log = Washer_log()
            washer_log.user = request.user
            washer_log.save()
            for Laund in Laundries:
                laundry = Laundry()
                laundry.washer_log = Washer_log(washer_log.pk)
                laundry.cabinet = Cabinet(Laund.pk)
                laundry.save()
            messages.success(request, 'ブックマークに保存しました')
            return redirect('/helpapp/washer_log')
        return redirect('/helpapp/washer/')
    else :
        return redirect('/accounts/login/')

laundryProject/helpapp/templates/laundry_tag_check/index.html
{% extends '../layout.html' %}
{% load static %}<!-- 必須 -->
{% block link%}
    <link rel="stylesheet" href="{% static 'css/LaundryTagCheck.css' %}">
    <!-- <script src="{% static 'js/TimeLine.js' %}"></script> -->
{% endblock %}
{% block content %}
<div class="progress">
    <img class="progress_img" src="{% static "pictures/progress_select.svg"%}" alt="">
</div>
<div><img src="{{file_url}}" alt="" class="laundryTagImg"></div>
<div class="msg">
    変更が必要な場合はマークをタップしてください
</div>
    

    <form action="{% url 'helpapp:judge_result' %}" method="POST">
        {% csrf_token %}
        <div class="selection-group">
            {% for tag in Laundry %}
                <input id={{tag}} type="radio" name="Laundry" value={{tag}} required>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
            <p class="red">※このタグは必ず選択してください</p>
        </div>
        <hr>
        <div class="selection-group">
            {% for tag in Bleach %}
                <input id={{tag}} type="radio" name="Bleach" value={{tag}}>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
        </div>
        <hr>
        <div class="selection-group">
            {% for tag in Nature %}
                <input id={{tag}} type="radio" name="Nature" value={{tag}}>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
        </div>
        <hr>
        <div class="selection-group">
            {% for tag in Iron %}
                <input id={{tag}} type="radio" name="Iron" value={{tag}}>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                    <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
        </div>
        <hr>
        <div class="selection-group">
            {% for tag in Tumble %}
                <input id={{tag}} type="radio" name="Tumble" value={{tag}}>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
        </div>
        <hr>
        <div class="selection-group">
            {% for tag in Dry %}
                <input id={{tag}} type="radio" name="Dry" value={{tag}}>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
        </div>
        <hr>
        <div class="selection-group">
            {% for tag in Wet %}
                <input id={{tag}} type="radio" name="Wet" value={{tag}}>
                <label for={{tag}}>
                    {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="radio" src="{% static img%}">
                    {% endwith %}
                </label>
            {% endfor %}
        </div>
        <div class="button">
            <input type="submit" value="OK" class="submit"></input>
        </div>
    </form>
    <script type="text/javascript">
        let submit = document.querySelector('input[type="submit"]');
        submit.addEventListener('click',  function() {
            window.scroll({ top: 0, behavior: "smooth" });
        });
        
        
        //ラジオボタン取得
        const radioBtns = Array.prototype.slice.call(document.querySelectorAll('input[type="radio"]'),0);
        //ラジオボタンが存在する場合は処理する
        if(radioBtns.length !== 0) {
        //ラジオボタンごとの設定
            radioBtns.forEach(function(radioBtn,index){
                //ラジオボタン識別番号設定
                radioBtn.radioIndex = index;
                //チェックフラグ設定
                if(radioBtn.checked) {
                radioBtn.checkFlg = true;
                } else {
                radioBtn.checkFlg = false;
                }
                //クリックイベント設定
                radioBtn.addEventListener('click',  function() {
                //番号を取得
                const thisIndex = this.radioIndex;
                //同じグループのラジオボタンを取得
                const group = Array.prototype.slice.call(document.querySelectorAll('input[type="radio"][name="'+radioBtn.name+'"]'),0);
                //未チェックの場合
                if(!this.checkFlg) {
                    //チェックフラグオン（checkedはJSで書かずともtrueになるので省略）
                    this.checkFlg = true;
                    //チェックした要素以外のフラグをfalseに
                    group.forEach(function(elm){
                    if(elm.checkFlg && elm.radioIndex !== thisIndex) {
                        elm.checkFlg = false;
                    }
                    });
                } else {
                    //既にチェックしている場合（リセット処理）
                    group.forEach(function(elm){
                    //チェックフラグがtrueかつ識別番号が一致するradio要素
                    if(elm.checkFlg && elm.radioIndex === thisIndex) {
                        //チェックフラグfalse
                        elm.checkFlg = false;
                        //ラジオボタンのチェック解除
                        elm.checked = false;
                    }
                    });
                }
                });
            });
        }
        let results = JSON.parse('{{ results|safe }}');
        for (let tag of results) {
            document.getElementById(tag).checked = true;
        }
        
    </script>
{% endblock %}

laundryProject/helpapp/templates/laundry_tag_check/result.html
{% extends '../layout.html' %}
{% load static %}<!-- 必須 -->
{% block link%}
    <link rel="stylesheet" href="{% static 'css/Result.css' %}">
{% endblock %}
{% block content %}
<div class="content">
    <div class="progress">
        <img class="progress_img" src="{% static "pictures/progress_result.svg"%}" alt="">
    </div>
    {% for message in messages %}
            <div {% if message.tags %}id="{{ message.tags }}"{% endif %}>
                <p>　×　　{{ message }}</p>
            </div>
    {% endfor %}
    <img src="{{file_url}}" class="laundryTagImg">

    <div class="result {{color}}"><p>{{result}}</p></div>
    <div class="details">
        <details>
            <summary class="belt">詳細</summary>
                {% for tag in tags %}
                <div class="tag">
                    <div class="tag_img">
                        {% with img="/pictures/"|add:tag|add:".png" %}
                        <img class="img" src="{% static img%}">
                        {% endwith %}
                    </div>
                    <div class="text"><div id="{{tag}}"></div></div>
                </div>
                {% endfor %}
        </details>
    </div>
    <div class="button">
        <a href="{% url 'helpapp:cabinet_form' %}">
            <button type="button" class="add_cabinet">タンスに追加</button>
        </a>
        <a href='{% url "helpapp:home" %}'>
            <button type="button" class="finish">完了</button>
        </a>
        {% if user.is_authenticated %}
            <a href='{% url "helpapp:judge_report" %}' class="ai_report" onclick='return confirm("AIの判定と洗濯タグに違いがありましたか？\n報告によりAIの性能向上に役立ちます");'>
                判定結果が違っていた場合
            </a>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
    let tags = JSON.parse('{{ tags_json|safe }}');
    let taginfos = eval({{ taginfos|safe }});
    for (const tag of tags) {
        let text = document.getElementById(tag); //宣言
        for (const taginfo of taginfos) {
            if ( tag == taginfo[0]) {
                text.innerHTML = (taginfo[1])
            }
        }
    }
</script>
{% endblock %}