laundryProject/helpapp/urls.py
from django.urls import path
from . import views


app_name = 'helpapp'

urlpatterns = [
    path('', views.helpapp, name='helpapp'),
    path('nologin', views.nologin, name='nologin'),
    path('home', views.home, name='home'),
    path('washer', views.washer, name='washer'),
    path('cabinet', views.cabinet, name='cabinet'),
    path('register', views.register, name='register'),
    path("user/",views.user, name="user"),
    path("judge",views.judge, name="judge"),
    path("judge_result",views.judge_result, name="judge_result"),
    path("judge_report",views.judge_report, name="judge_report"),
    path("cabinet_judge",views.cabinet_judge, name="cabinet_judge"),
    path("cabinet_form",views.cabinet_form, name="cabinet_form"),
    path("cabinet_add",views.cabinet_add, name="cabinet_add"),
    path("cabinet_detail/<int:pk>/",views.cabinet_detail, name="cabinet_detail"),
    path("washer_add",views.washer_add, name="washer_add"),
    path("washer_add_redirect",views.washer_add_redirect, name="washer_add_redirect"),
    path("washer_judge",views.washer_judge, name="washer_judge"),
    path("washer_complete",views.washer_complete, name="washer_complete"),
    path("washers_delete",views.washers_delete, name="washers_delete"),
    path("washer_clear",views.washer_clear, name="washer_clear"),
    path("laundry_tag_check",views.laundry_tag_check, name="laundry_tag_check"),
    path("cabinet_delete/<int:pk>/",views.cabinet_delete, name="cabinet_delete"),
    path("cabinets_delete",views.cabinets_delete, name="cabinets_delete"),
    path("test",views.testYolo, name="test"),
    path("washer_log_add",views.washer_log_add, name="washer_log_add"),
    path("washer_log",views.washer_log, name="washer_log"),
    path("washer_log_detail/<int:pk>/",views.washer_log_detail, name="washer_log_detail"),
    path("washer_log_delete/<int:pk>/",views.washer_log_delete, name="washer_log_delete"),
    path("log_to_washer/<int:id>/",views.log_to_washer, name="log_to_washer"),
    path("report_admin",views.report_admin, name="report_admin"),
    path("report_commit",views.report_commit, name="report_commit"),
]

laundryProject/laundryProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('helpapp/', include('helpapp.urls')),  #URLにhelpapp/って指定されたら includeを呼び出す
    path('admin/', admin.site.urls),    #admin入るため
    path('', RedirectView.as_view(url='/helpapp/')), #URLに何も入れないとhelpapp/になる
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像読むのに必要

laundryProject/templates/layout.html
{% load static %}<!-- 必須 -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="その洗濯の悩み、AIが解決します!!!誰もが初めての洗濯でぶつかる「洗い方がわからない」という悩み。私たちのシステムでは、洋服の洗濯タグを撮影するだけで、AIが洗い方と干し方を教えてくれ、あなたの洗濯の悩みを解決します。">
    <meta name="keywords" content="洗濯, AI, 洗濯タグ, 洗濯表示, laundry ">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static "pictures/icon.svg"%}">
    
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <title>{{message}} - AI Tag Checker</title>
    {% block link %}
    
    {% endblock %}
</head>
<body ontouchstart="">
    <div class="container">
        <div id="header">
                <img class="header_icon" src="{% static "pictures/wave.png"%}" alt="">
        </div>
        {% block content %}
        {% endblock %}
        <footer class="footer">
            <ul>
                <li id="washer"><a href="{% url 'helpapp:washer' %}"><img src="{% static "pictures/washer.svg"%}"></a></li>
                <li id="cabinet"><a href="{% url 'helpapp:cabinet' %}"><img src="{% static "pictures/cabinet.svg"%}"></a></li>
                <li id="home"><a href="{% url 'helpapp:home' %}"><img src="{% static "pictures/camera.svg"%}"></a></li>
                <li id="bookmark"><a href="{% url 'helpapp:washer_log' %}"><img src="{% static "pictures/bookmark.svg"%}"></a></li>
                {% comment %}<li id="timeline"><a href="{% url 'helpapp:timeline' %}"><img src="{% static "pictures/timeline.svg"%}"></a></li>{% endcomment%}
                <li id="user"><a href="{% url 'helpapp:user' %}"><img src="{% static "pictures/user.svg"%}"></a></li>
            </ul>
        </footer>
    </div>
    <script>        
        let success = document.getElementById('success');
        let error = document.getElementById('error');
        if(success) {
            success.addEventListener('click', () => { 
                success.classList.add('hidden');  
            }) 
        };
        if(error) {
            error.addEventListener('click', () => { 
                error.classList.add('hidden');  
            }) 
        };
        const ON = JSON.parse('{{ ON|safe }}');
        var id = document.getElementById(ON);
        id.classList.add("ON");
    </script>
</body>
</html>